// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eccpujigpkaviolnqlmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjY3B1amlncGthdmlvbG5xbG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjY0MjcsImV4cCI6MjA1OTgwMjQyN30.UzgSZUymFselaIdMYFQJmge9Z5Y5rARYSTGmYROEUlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);